# ======================================
# TOPOLOGY and EXTERNAL DEPENDENCIES
# ======================================
application:
  name: sample-grpc

# ======================================
# Spring Boot
# ======================================
spring:
  application:
    name: ${application.name}

# ======================================
# Management
# ======================================
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
