# ======================================
# TOPOLOGY and EXTERNAL DEPENDENCIES
# ======================================
application:
  name: sample-workflow-temporal

# ======================================
# Spring Boot
# ======================================
spring:
  application:
    name: ${application.name}

# ======================================
# Management
# ======================================
server:
  port: 8080

observability:
  metrics:
    report.sec: 1
  jaeger:
    enabled: true
    endpoint: "http://localhost:14250"

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus
  endpoint:
    # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics
    metrics:
      enabled: true
    health:
      # ALWAYS | NEVER
      show-details: ALWAYS

info:
  # https://www.callicoder.com/spring-boot-actuator/
  app:
    name: ${application.name}
  observability:
    jaeger:
      enable: ${jaeger.enable}
      endpoint: ${jaeger.endpoint}
