# ======================================
# TOPOLOGY and EXTERNAL DEPENDENCIES
# ======================================
application:
  name: sample-workflow-temporal
  persistence:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# ======================================
# Spring Boot
# ======================================
spring:
  application:
    name: ${application.name}

  # R2DBC
  r2dbc:
    url: ${application.persistence.url}
    username: ${application.persistence.username}
    password: ${application.persistence.password}
    initialization-mode: always

logging:
  level:
    org.springframework.data.r2dbc: ${LOG_LEVEL_DB_SQL:DEBUG}
    org.springframework.transaction: ${LOG_LEVEL_DB_TXN:TRACE}

# ======================================
# Management
# ======================================
server:
  port: 8080

observability:
  metrics:
    report.sec: 1
  jaeger:
    enabled: true
    endpoint: "http://localhost:14250"

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus
  endpoint:
    # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics
    metrics:
      enabled: true
    health:
      # ALWAYS | NEVER
      show-details: ALWAYS

info:
  # https://www.callicoder.com/spring-boot-actuator/
  app:
    name: ${application.name}
  observability:
    jaeger:
      enable: ${jaeger.enable}
      endpoint: ${jaeger.endpoint}
